#pragma once
#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Travelling)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Travelling_DynamicBoarding)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Travelling_Running)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Travelling_Walking)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Travelling_Skiing)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Travelling_Cruising)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Travelling_Gliding)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Travelling_Skating)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Stationary)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Stationary_Waiting)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Stationary_StaticBoarding)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Stationary_Queueing)
