#include "Buildables and technologies.h"

UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable, "Buildable", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Framework, "Buildable.Framework", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Framework_Topology, "Buildable.Framework.Topology", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Framework_Topology_Line, "Buildable.Framework.Topology.Line", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Framework_Topology_Loop, "Buildable.Framework.Topology.Loop", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Framework_Topology_Polygon, "Buildable.Framework.Topology.Polygon", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Framework_Topology_Point, "Buildable.Framework.Topology.Point", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Framework_Placement, "Buildable.Framework.Placement", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Framework_Placement_Internal, "Buildable.Framework.Placement.Internal", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Framework_Placement_Waypoint, "Buildable.Framework.Placement.Waypoint", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Framework_Placement_Midstation, "Buildable.Framework.Placement.Midstation", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Framework_Placement_Terminus, "Buildable.Framework.Placement.Terminus", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Aspect, "Buildable.Aspect", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Aspect_Submesh, "Buildable.Aspect.Submesh", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Aspect_Submesh_Cable, "Buildable.Aspect.Submesh.Cable", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Aspect_Submesh_Cable_Clockwise, "Buildable.Aspect.Submesh.Cable.Clockwise", "List of transforms to attach a clockwise cable route.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Aspect_Submesh_Cable_Widdershins, "Buildable.Aspect.Submesh.Cable.Widdershins", "List of transforms to attach a widdershins cable route.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Aspect_Submesh_Pulley, "Buildable.Aspect.Submesh.Pulley", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Aspect_Submesh_Pulley_Liftcable, "Buildable.Aspect.Submesh.Pulley.Liftcable", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Aspect_Submesh_SurfaceSpline, "Buildable.Aspect.Submesh.SurfaceSpline", "Signals the SurfaceSplinePrismSubsystem to render a Spline Prism along the landscape surface, following the Buildable's spline.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Aspect_MassEntity, "Buildable.Aspect.MassEntity", "Flags an asset as spawning via MassEntity.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Aspect_MassEntity_Spline, "Buildable.Aspect.MassEntity.Spline", "Flags an asset as spawning via MassEntity with spline-directed movement when completed. Most likely declared at the Buildable Actor level.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Aspect_MassEntity_Spline_SkiChair, "Buildable.Aspect.MassEntity.Spline.SkiChair", "Spawns SkiChair entities, adhering to the ski chair boarding equation.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Aspect_MassEntity_TransformSet, "Buildable.Aspect.MassEntity.TransformSet", "Flags an asset as spawning via MassEntity with Spawn locations given by a FSubMeshTransformSet. Declared at the Buildable Component level.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain, "Buildable.Domain", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport, "Buildable.Domain.Transport", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle, "Buildable.Domain.Transport.Vehicle", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Cabin, "Buildable.Domain.Transport.Vehicle.Cabin", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Cabin_Gondola, "Buildable.Domain.Transport.Vehicle.Cabin.Gondola", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Cabin_Gondola_Enclosed, "Buildable.Domain.Transport.Vehicle.Cabin.Gondola.Enclosed", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Cabin_SkiChair, "Buildable.Domain.Transport.Vehicle.Cabin.SkiChair", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Cabin_SkiChair_Enclosed, "Buildable.Domain.Transport.Vehicle.Cabin.SkiChair.Enclosed", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity, "Buildable.Domain.Transport.Vehicle.Capacity", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity_Small, "Buildable.Domain.Transport.Vehicle.Capacity.Small", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity_Small_2, "Buildable.Domain.Transport.Vehicle.Capacity.Small.2", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity_Small_4, "Buildable.Domain.Transport.Vehicle.Capacity.Small.4", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity_Medium, "Buildable.Domain.Transport.Vehicle.Capacity.Medium", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity_Medium_6, "Buildable.Domain.Transport.Vehicle.Capacity.Medium.6", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity_Medium_8, "Buildable.Domain.Transport.Vehicle.Capacity.Medium.8", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity_Large, "Buildable.Domain.Transport.Vehicle.Capacity.Large", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity_Large_12, "Buildable.Domain.Transport.Vehicle.Capacity.Large.12", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity_Large_16, "Buildable.Domain.Transport.Vehicle.Capacity.Large.16", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity_Large_24, "Buildable.Domain.Transport.Vehicle.Capacity.Large.24", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity_Large_32, "Buildable.Domain.Transport.Vehicle.Capacity.Large.32", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Capacity_Large_40, "Buildable.Domain.Transport.Vehicle.Capacity.Large.40", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Drive, "Buildable.Domain.Transport.Vehicle.Drive", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Drive_Mounting, "Buildable.Domain.Transport.Vehicle.Drive.Mounting", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Drive_Mounting_Detachable, "Buildable.Domain.Transport.Vehicle.Drive.Mounting.Detachable", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Drive_Mounting_Fixed, "Buildable.Domain.Transport.Vehicle.Drive.Mounting.Fixed", "Vehicle's drive mechanism requires it to maintain a fixed speed along a spline.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Drive_Source, "Buildable.Domain.Transport.Vehicle.Drive.Source", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Drive_Source_Bullwheel, "Buildable.Domain.Transport.Vehicle.Drive.Source.Bullwheel", "Large wheel used to drive a chair lift cable.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Drive_Source_Cable, "Buildable.Domain.Transport.Vehicle.Drive.Source.Cable", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Drive_Source_Cable_Loop, "Buildable.Domain.Transport.Vehicle.Drive.Source.Cable.Loop", "Vehicle's drive source is a cable that runs in a continuous loop.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Drive_Source_Cable_Shuttle, "Buildable.Domain.Transport.Vehicle.Drive.Source.Cable.Shuttle", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Seating, "Buildable.Domain.Transport.Vehicle.Seating", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Seating_Wooden, "Buildable.Domain.Transport.Vehicle.Seating.Wooden", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Seating_Plastic, "Buildable.Domain.Transport.Vehicle.Seating.Plastic", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Seating_Padded, "Buildable.Domain.Transport.Vehicle.Seating.Padded", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Vehicle_Seating_Unwettable, "Buildable.Domain.Transport.Vehicle.Seating.Unwettable", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Station, "Buildable.Domain.Transport.Station", "Locations  where guests can board and alight vehicular transport.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Station_Alighting, "Buildable.Domain.Transport.Station.Alighting", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Station_Alighting_Indoor, "Buildable.Domain.Transport.Station.Alighting.Indoor", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Station_Alighting_Outdoor, "Buildable.Domain.Transport.Station.Alighting.Outdoor", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Station_Boarding, "Buildable.Domain.Transport.Station.Boarding", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Station_Boarding_Indoor, "Buildable.Domain.Transport.Station.Boarding.Indoor", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Station_Boarding_Outdoor, "Buildable.Domain.Transport.Station.Boarding.Outdoor", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Station_Boarding_Outdoor_ConveyorBoard, "Buildable.Domain.Transport.Station.Boarding.Outdoor.ConveyorBoard", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Station_Boarding_Outdoor_ConveyorIntake, "Buildable.Domain.Transport.Station.Boarding.Outdoor.ConveyorIntake", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Station_Boarding_Outdoor_Static, "Buildable.Domain.Transport.Station.Boarding.Outdoor.Static", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Station_Cableguide, "Buildable.Domain.Transport.Station.Cableguide", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Route, "Buildable.Domain.Transport.Route", "Types of Transport Route")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Route_Surface, "Buildable.Domain.Transport.Route.Surface", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Route_Surface_Rail, "Buildable.Domain.Transport.Route.Surface.Rail", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Route_Surface_Road, "Buildable.Domain.Transport.Route.Surface.Road", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Route_Surface_Piste, "Buildable.Domain.Transport.Route.Surface.Piste", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Route_Surface_Piste_Downhill, "Buildable.Domain.Transport.Route.Surface.Piste.Downhill", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Route_Surface_Piste_Uphill, "Buildable.Domain.Transport.Route.Surface.Piste.Uphill", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Route_Aerial, "Buildable.Domain.Transport.Route.Aerial", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Route_Aerial_Cable, "Buildable.Domain.Transport.Route.Aerial.Cable", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Route_Aerial_Cable_Shuttle, "Buildable.Domain.Transport.Route.Aerial.Cable.Shuttle", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Route_Aerial_Cable_Loop, "Buildable.Domain.Transport.Route.Aerial.Cable.Loop", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Transport_Route_Aerial_Aeroplane, "Buildable.Domain.Transport.Route.Aerial.Aeroplane", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Accommodation, "Buildable.Domain.Accommodation", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Trade, "Buildable.Domain.Trade", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Trade_Apparel, "Buildable.Domain.Trade.Apparel", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Trade_Apparel_LightAdaptiveGoggles, "Buildable.Domain.Trade.Apparel.LightAdaptiveGoggles", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Trade_Apparel_AntiMistGoggles, "Buildable.Domain.Trade.Apparel.AntiMistGoggles", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Trade_Apparel_SkiHelmets, "Buildable.Domain.Trade.Apparel.SkiHelmets", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Service, "Buildable.Domain.Service", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Utility, "Buildable.Domain.Utility", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Domain_Amenity, "Buildable.Domain.Amenity", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Status, "Buildable.Status", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Status_Open, "Buildable.Status.Open", "The Buildable is admitting guests.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Buildable_Status_Closed, "Buildable.Status.Closed", "The Buildable is not admitting guests")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology, "Technology", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation, "Technology.SubstantiveInnovation", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience, "Technology.SubstantiveInnovation.MaterialScience", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_NaturalMaterials, "Technology.SubstantiveInnovation.MaterialScience.NaturalMaterials", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_NaturalMaterials_Wood, "Technology.SubstantiveInnovation.MaterialScience.NaturalMaterials.Wood", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_NaturalMaterials_Cotton, "Technology.SubstantiveInnovation.MaterialScience.NaturalMaterials.Cotton", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Metallurgy, "Technology.SubstantiveInnovation.MaterialScience.Metallurgy", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Metallurgy_Steel, "Technology.SubstantiveInnovation.MaterialScience.Metallurgy.Steel", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Metallurgy_Aluminium, "Technology.SubstantiveInnovation.MaterialScience.Metallurgy.Aluminium", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Metallurgy_Titanium, "Technology.SubstantiveInnovation.MaterialScience.Metallurgy.Titanium", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Plastics, "Technology.SubstantiveInnovation.MaterialScience.Plastics", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Plastics_ThermalStability, "Technology.SubstantiveInnovation.MaterialScience.Plastics.ThermalStability", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Plastics_ThermalStability_LowTemperaturePlasticity, "Technology.SubstantiveInnovation.MaterialScience.Plastics.ThermalStability.LowTemperaturePlasticity", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Plastics_ThermalStability_LowTemperatureElasticity, "Technology.SubstantiveInnovation.MaterialScience.Plastics.ThermalStability.LowTemperatureElasticity", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Plastics_ThermalStability_MemoryFoam, "Technology.SubstantiveInnovation.MaterialScience.Plastics.ThermalStability.MemoryFoam", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Plastics_SyntheticTextiles, "Technology.SubstantiveInnovation.MaterialScience.Plastics.SyntheticTextiles", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Plastics_SyntheticTextiles_WaterproofFabrics, "Technology.SubstantiveInnovation.MaterialScience.Plastics.SyntheticTextiles.WaterproofFabrics", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Plastics_SyntheticTextiles_BreathableFabrics, "Technology.SubstantiveInnovation.MaterialScience.Plastics.SyntheticTextiles.BreathableFabrics", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Plastics_OpticalPolymers, "Technology.SubstantiveInnovation.MaterialScience.Plastics.OpticalPolymers", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Plastics_OpticalPolymers_TranslucentPolymers, "Technology.SubstantiveInnovation.MaterialScience.Plastics.OpticalPolymers.TranslucentPolymers", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Plastics_OpticalPolymers_PolarizingTranslucency, "Technology.SubstantiveInnovation.MaterialScience.Plastics.OpticalPolymers.PolarizingTranslucency", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_Plastics_OpticalPolymers_ReactiveTranslucency, "Technology.SubstantiveInnovation.MaterialScience.Plastics.OpticalPolymers.ReactiveTranslucency", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_AdvancedComposites, "Technology.SubstantiveInnovation.MaterialScience.AdvancedComposites", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_AdvancedComposites_CarbonFibre, "Technology.SubstantiveInnovation.MaterialScience.AdvancedComposites.CarbonFibre", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_MaterialScience_AdvancedComposites_ExoticLaminates, "Technology.SubstantiveInnovation.MaterialScience.AdvancedComposites.ExoticLaminates", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_TechnicalSolutions, "Technology.SubstantiveInnovation.TechnicalSolutions", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_TechnicalSolutions_DetachableCableMount, "Technology.SubstantiveInnovation.TechnicalSolutions.DetachableCableMount", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_TechnicalSolutions_GatedBoarding, "Technology.SubstantiveInnovation.TechnicalSolutions.GatedBoarding", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_TechnicalSolutions_Apparel, "Technology.SubstantiveInnovation.TechnicalSolutions.Apparel", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_TechnicalSolutions_Apparel_OnBootSnowboardBindings, "Technology.SubstantiveInnovation.TechnicalSolutions.Apparel.OnBootSnowboardBindings", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_SubstantiveInnovation_TechnicalSolutions_Apparel_QuickReleaseSkiBindings, "Technology.SubstantiveInnovation.TechnicalSolutions.Apparel.QuickReleaseSkiBindings", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_ContinuousImprovement, "Technology.ContinuousImprovement", "")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_ContinuousImprovement_UnitCost, "Technology.ContinuousImprovement.UnitCost", "Reduce the unit cost of this component")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_ContinuousImprovement_UnitWeight, "Technology.ContinuousImprovement.UnitWeight", "Reduce the unloaded weight of each unit")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_ContinuousImprovement_BuildTime, "Technology.ContinuousImprovement.BuildTime", "Reduce the build time")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_ContinuousImprovement_AttritionRate, "Technology.ContinuousImprovement.AttritionRate", "Reduce the rate at which this component becomes worn leading to replacement.")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_ContinuousImprovement_LoadBearingCapacity, "Technology.ContinuousImprovement.LoadBearingCapacity", "Increase the load-bearing capacity of this component")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Technology_ContinuousImprovement_CruisingVelocity, "Technology.ContinuousImprovement.CruisingVelocity", "Increase the base cruising velocity of this vehicle")
